// app/(customer)/_components/NotificationsButton.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Bell, CheckCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

interface Notification {
  id: string;
  title: string;
  body: string;
  is_read: boolean;
  created_at: string;
}

/** Same "honest, computed-from-real-data" relative time as orders/_components/timeAgo.ts,
 * duplicated locally rather than importing across route groups for one small helper. */
function timeAgo(isoDate: string): string {
  const ms = Date.now() - new Date(isoDate).getTime();
  const minutes = Math.max(0, Math.round(ms / 60_000));
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours} ${hours === 1 ? "hour" : "hours"} ago`;
  const days = Math.round(hours / 24);
  return `${days} ${days === 1 ? "day" : "days"} ago`;
}

/**
 * Real notifications, generated by a DB trigger on order status changes
 * (0038_customer_notifications.sql) — not the always-on decorative dot this
 * button used to render regardless of whether anything had happened. The
 * dot only shows when `unreadCount > 0`, and a Realtime subscription keeps
 * it live without polling (the `notifications` table is in the
 * `supabase_realtime` publication).
 */
export function NotificationsButton() {
  const [isOpen, setIsOpen] = useState(false);
  const [items, setItems] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // `cancelled` guards against React StrictMode's dev-only double-invoke
    // of this effect: mount -> cleanup -> mount again, synchronously. The
    // first mount's cleanup calls removeChannel(), but that's genuinely
    // async (it awaits an unsubscribe round trip before the channel is torn
    // down - see @supabase/realtime-js's RealtimeClient.removeChannel()), so
    // it hasn't finished by the time the second mount runs. supabase.channel()
    // dedupes by topic and would hand back that still-joined channel, and
    // calling .on() on an already-subscribed channel is exactly what threw
    // "cannot add postgres_changes callbacks ... after subscribe()". Awaiting
    // the removal of any stale same-topic channel before subscribing again
    // closes that window.
    let cancelled = false;
    const supabase = createClient();
    let channel: ReturnType<typeof supabase.channel> | null = null;

    async function loadUnreadCount(userId: string) {
      const { count } = await supabase
        .from("notifications")
        .select("id", { count: "exact", head: true })
        .eq("customer_id", userId)
        .eq("is_read", false);
      if (!cancelled) setUnreadCount(count ?? 0);
    }

    void (async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user || cancelled) return;

      await loadUnreadCount(user.id);
      if (cancelled) return;

      const topic = `notifications:${user.id}`;
      const stale = supabase.getChannels().find((c) => c.topic === `realtime:${topic}`);
      if (stale) await supabase.removeChannel(stale);
      if (cancelled) return;

      channel = supabase
        .channel(topic)
        .on(
          "postgres_changes",
          { event: "*", schema: "public", table: "notifications", filter: `customer_id=eq.${user.id}` },
          () => void loadUnreadCount(user.id),
        )
        .subscribe();
    })();

    return () => {
      cancelled = true;
      if (channel) void supabase.removeChannel(channel);
    };
  }, []);

  useEffect(() => {
    if (!isOpen) return;
    function onClickOutside(event: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, [isOpen]);

  async function handleOpen() {
    setIsOpen((open) => !open);
    if (items.length > 0 || isOpen) return;

    const supabase = createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return;

    const { data } = await supabase
      .from("notifications")
      .select("id, title, body, is_read, created_at")
      .eq("customer_id", user.id)
      .order("created_at", { ascending: false })
      .limit(15);
    setItems(data ?? []);
  }

  async function handleMarkAllRead() {
    const supabase = createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return;

    await supabase.from("notifications").update({ is_read: true }).eq("customer_id", user.id).eq("is_read", false);
    setItems((prev) => prev.map((n) => ({ ...n, is_read: true })));
    setUnreadCount(0);
  }

  return (
    <div className="relative" ref={containerRef}>
      <button
        onClick={() => void handleOpen()}
        className="relative rounded-full p-2 transition-colors hover:bg-black/5"
        aria-label={`Notifications${unreadCount > 0 ? `, ${unreadCount} unread` : ""}`}
      >
        <Bell className="size-5 text-[#5B403C] sm:size-4" />
        {unreadCount > 0 && (
          <span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-[#B61913]" />
        )}
      </button>

      {isOpen && (
        <div className="absolute right-0 top-full z-50 mt-2 max-h-[70vh] w-80 overflow-y-auto rounded-2xl border border-[#E4BEB8] bg-white shadow-lg">
          <div className="flex items-center justify-between border-b border-[#E4BEB8] px-4 py-3">
            <span className="font-sora text-sm font-semibold text-[#1C1B1B]">Notifications</span>
            {unreadCount > 0 && (
              <button
                onClick={() => void handleMarkAllRead()}
                className="flex items-center gap-1 font-inter text-xs font-medium text-[#B61913] hover:underline"
              >
                <CheckCheck className="size-3.5" />
                Mark all read
              </button>
            )}
          </div>

          {items.length === 0 ? (
            <p className="px-4 py-8 text-center font-inter text-sm text-[#5B403C]">
              Nothing here yet — updates about your orders will show up as they happen.
            </p>
          ) : (
            <ul>
              {items.map((n) => (
                <li key={n.id} className={`border-b border-[#F0EDED] px-4 py-3 last:border-b-0 ${n.is_read ? "" : "bg-[#FFF6F5]"}`}>
                  <div className="flex items-start gap-2">
                    {!n.is_read && <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-[#B61913]" />}
                    <div className={n.is_read ? "ml-3.5" : ""}>
                      <p className="font-inter text-sm font-semibold text-[#1C1B1B]">{n.title}</p>
                      <p className="mt-0.5 font-inter text-xs text-[#5B403C]">{n.body}</p>
                      <p className="mt-1 font-inter text-[11px] text-[#5B403C]/70">{timeAgo(n.created_at)}</p>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
